# Generated by Django 5.0.1 on 2024-03-15 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medication Name')),
                ('frequency', models.IntegerField(help_text='Número de horas entre doses', verbose_name='Frequency of Dosage (hours)')),
                ('dose', models.CharField(help_text="Example: '1 comprimido', '10 mg'", max_length=100, verbose_name='Dose')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date and Time')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if the medication does not have an end date.', null=True, verbose_name='End Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
